import * as React from "react";
import Head from "next/head";
import Image from "next/image";
import { Flex } from "@chakra-ui/react";
import { motion } from "framer-motion";
import PanenUdangImg from "../public/PanenUdanghead.png";

export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Flex
        style={{
          top: "50%",
          left: "50%",
          // width: "100%",
          // height: "100%",
          position: "fixed",
        }}
      >
        <motion.div
          animate={{
            scale: [0.5, 1, 1, 0.5, 0.5],
            rotate: [0, 270, 0, 270, 0],
            borderRadius: ["20%", "20%", "50%", "50%", "20%"],
          }}
        >
          <Image src={PanenUdangImg} alt="panen udang header" />
        </motion.div>
      </Flex>
    </>
  );
}
